version: '3'

services:
  db:
    image: postgres

    container_name: coffee-database

    restart: always

    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: iluvcoffee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123

  test-db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: pass123
